# Generated by Django 4.2.8 on 2023-12-08 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdialog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userdialog',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdialog',
            name='sender',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userdialog',
            unique_together={('dialog', 'sender', 'receiver')},
        ),
        migrations.RemoveField(
            model_name='userdialog',
            name='user',
        ),
    ]
