# Generated by Django 4.2.8 on 2023-12-08 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userdialog_unique_together_userdialog_receiver_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdialog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userdialog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userdialog',
            unique_together={('dialog', 'user')},
        ),
        migrations.RemoveField(
            model_name='userdialog',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='userdialog',
            name='sender',
        ),
    ]
