# Generated by Django 4.2.8 on 2023-12-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_userdialog_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdialog',
            unique_together=set(),
        ),
    ]
