# Generated by Django 4.2.8 on 2023-12-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_userdialog_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdialog',
            unique_together={('user1', 'user2')},
        ),
    ]
